name: trade_trackr
description: "TradeTrackr is an offline trading journal app that helps traders easily record and manage their trades. It stores all data locally on the device, letting users track performance, analyze results, and export data manually or automatically as backups. With a clean and user-friendly design, TradeTrackr is a practical tool for traders who want a simple, reliable, and private way to keep a trading diary"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  uuid: ^4.1.0
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  go_router: ^16.2.1
  flutter_dotenv: ^6.0.0
  logger: ^2.6.1
  shadcn_ui: ^0.31.8
  drift: ^2.29.0
  drift_flutter: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  mockito: ^5.1.0
  drift_dev: ^2.29.0

flutter:

  uses-material-design: true
  assets:
    - assets/dev/.env
    - assets/prod/.env



