import '../enums/severity.dart';

/// A recommendation generated by the analysis engine.
class Recommendation {
  final String title;
  final String description;
  final Severity severity;

  const Recommendation({
    required this.title,
    required this.description,
    required this.severity,
  });
}
